### ISSUE TITLE
Why I can not use?

### ISSUE THREAD

**Issue by tzjvon** [tm-minty/sublime-text-2-image2base64#10]
When I press Ctrl+i+b in Sublime Text 3.
But clipboard has no base64 code!!!? #

**Comment by tm-minty** [comment]
When you press Ctrl+i+b plugin searchs all supported images in opened folders and then shows you dropdown with images list. When you select image plugin converts it into base64 and put into clipboard. It have to be looked like this:

![output](https://cloud.githubusercontent.com/assets/1011262/21841778/d2ce645e-d7f4-11e6-8811-2c4bc2f2e197.gif)

**Comment by tzjvon** [comment]
OK,Thank you very very much!
