### ISSUE TITLE
[Feature request] External link conversion

### ISSUE THREAD

**Issue by Kristinita** [tm-minty/sublime-text-2-image2base64#11]
### 1. Request

It would be nice, if will be possible convert external links, not merely images from sidebar.

### 2. Justification

I used to quick download my images in third-party servers, and I need convert Imgur images, not my sidebar images.

### 3. Desirable behavior

I select link **<http://i.imgur.com/Ir1oYnF.jpg>** → <kbd>Ctrl+Shift+P</kbd> → `Image2Base64: Convert External Link` → `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSjAndSoOn…` transfer to my clipboard.

Thanks.

**Comment by tm-minty** [comment]
Great idea!
I'll do it asap. Thanks for participating

**Comment by tm-minty** [comment]
Done. Press Ctrl+u+b and input image url (input pannel in the bottom of window).
