### ISSUE TITLE
[Feature request] Break long URI

### ISSUE THREAD

**Issue by Kristinita** [tm-minty/sublime-text-2-image2base64#12]
### 1. Request

It would be nice, if long Data URI will break to new line. Data URI [**will be valid**](https://github.com/SublimeTextIssues/Core/issues/513#issuecomment-281264250).

### 2. Justification

In Sublime Text if line length have more than 16383 characters, syntax for line don't highlight. See [**more details**](https://github.com/SublimeTextIssues/Core/issues/513#issuecomment-281254591).

### 3. Desirable behavior

If in package settings `"split_long_line": true`, 16000 characters of long Data URI stay in current line, next 16000 characters wrap to next line, next 16000 characters wrap to next line and so on.

Thanks.

**Comment by tm-minty** [comment]
Done. In ST3 by default line length is 16000 characters, in ST2 by default line splitting is off. You can change/enable it in settings file: Preferencies > Package Settings > Image2Base64 > ...

**Comment by Kristinita** [comment]
@tm-minty, now images not displayed for me:

+ My image: **<http://i.imgur.com/VNgrSxS.jpg>**,
+ Previous behavior: **<http://codepen.io/Kristinita/pen/peWZwx>** — good,
+ Actual behavior: **<http://codepen.io/Kristinita/pen/qrPypb>** — bad.

I reproduce the problem in Sublime Text.

Thanks.

**Comment by tm-minty** [comment]
I've tested splitting in <img> tag and pasted base64 in src attribute. The problem is in line ending. CSS required backslash. I'll try to move line splitting to separate command after pasting base64.

**Comment by tm-minty** [comment]
v1.1.2: Added new command "Image2Base64: Paste base64 into CSS" into command pallete.

**Comment by Kristinita** [comment]
@tm-minty , if in my CSS file I select `Image2Base64: Paste base64 into CSS` Data URI don't break to new lines for me.

Thanks.

**Comment by Kristinita** [comment]
@tm-minty, <kbd>Ctrl+Shift+P</kbd> → `Image2Base64: Convert image from opened folders and files` → I select image → I place cursor between parentheses in `background-image: url()` in any `css` file → <kbd>Ctrl+Shift+P</kbd> → `Image2Base64: Paste base64 into CSS` → data URI don't break for me. What I do wrong?

Thanks.
